#
# Makefile for the input core drivers.
#

# Each configuration option enables a list of files.
# sensor drivers

obj-$(CONFIG_SENSORS_AP3425H)   += ap3425h/
obj-$(CONFIG_SENSORS_BMC156)    += bmc156/

obj-$(CONFIG_HALL_SENSOR) += hall/
