#FT5726 touchpanel driver

obj-y         += focaltech_core.o
obj-y         += focaltech_ctl.o
obj-y         += focaltech_ex_fun.o
obj-y         += focaltech_gesture.o
obj-y         += focaltech_flash.o
obj-y	      += ft5726_test/

